### ISSUE TITLE
RTSP Camera link Not Working on KAN but worked Perfectly on VLC

### ISSUE THREAD

**Issue by JMH-Jarbydev** [Azure/KAN#250]
HI,

I've set up the RTSP Camera Feed on KAN, but when I clicked on View I don't get the live feed. just a Square Grey box.
I test the RTSP Url on VLC and worked Great without issues.

rtsp://admin:password@IPaddress:554/cam/realmonitor?channel=1&subtype=0
rtsp://192.168.0.1:80
rtsp://admin:password@IPaddress:80
Thanks

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/69280541/227329044-e9afe361-e25e-4fa2-92b4-0bb68753a42d.png">

**Comment by Haishi2016** [comment]
Hi @JMH-Jarbydev, is your camera local to the Kubernetes cluster? Since we are reaching out from the Kubernetes cluster to the RTSTP address, the address needs to be resolvable from the cluster. For example, if you've deployed KAN on AKS and your camera is local, the preview wouldn't work as the camera address can't be resolved from AKS.

**Comment by Haishi2016** [comment]
Closing for no activities.
